### ISSUE TITLE
KA10: ITS hangs after purifying programs

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#34]
I have started on an automated build of KA ITS and all programs.

I have encountered a problem shortly after purification.  The first two programs built are MIDAS and DDT.  They are first assembled with MIDAS, and then loaded into DDT for running the PURIFY routine.  Shortly after this, ITS starts to act weirdly.  It hangs; sometimes it's possible to get its attention by typing ^G, sometimes not.

**Comment by larsbrinkhoff** [comment]
When the script has assembled midas, it goes on to purification:

```
*:job midas
!
*:load sysbin;midas bin
*purify$g
:$ Purified, type CR to dump $
*:PDUMP SYS;TS MIDAS
DB     HACTRN SYS    _DUMP_ OUTPUT WRITE  12:10:50
DB     HACTRN SYS    TS     MIDAS  DELRNM 12:10:50
*:kill
```

The `:kill` command never finishes.

**Comment by larsbrinkhoff** [comment]
If I log in and try to purify manually, `:kill` hangs, but I'm able to ^G it.

```
m$j!
*$l sysbin; midas bin
*purify$g
:$ Purified, type CR to dump $
*:PDUMP SYS;TS MIDAS
___002 HACTRN SYS    _DUMP_ OUTPUT WRITE
___002 HACTRN SYS    TS     MIDAS  DELRNM
*:kill
 QUIT?
sys^F
ML   SYS
FREE BLOCKS #2=4694 #3=6771
  2   :MSGS  TIMES  1 ! 12/7/2017 04:16:51

**Comment by larsbrinkhoff** [comment]
I have now pushed everything to my ITS ka10 branch.  A "make" should exhibit the problem, but takes a very long time to finish.

**Comment by larsbrinkhoff** [comment]
TECO built in KS ITS doesn't work in the KA10 simulator.

However, EMACS works.  And of course DDT and MIDAS.  These were all built and purified in KS ITS.

**Comment by rcornwell** [comment]
I pushed out a patch that seems to solve this. I am still trying to get simulator through PT test. So please don't close this issue yet.

**Comment by larsbrinkhoff** [comment]
Yes, purifying seem to work now.  MIDAS is rebuilt and purified and the new binary can assemble DDT.  Which is also purified successfully.

**Comment by larsbrinkhoff** [comment]
TECO still doesn't work, so that should be a separate problem.

**Comment by larsbrinkhoff** [comment]
With this fix in place, CHANNA; RAKASH NETIME hangs.  It's started when ITS boots, so it blocks logins.

**Comment by rcornwell** [comment]
I might solve this problem when I get through the PT testing. It is having a problem with a page not being refreshed, but I have not figured out why.

**Comment by rcornwell** [comment]
This should be working in current commit. LISP still hangs during build.

**Comment by larsbrinkhoff** [comment]
Seems good!
